simulator:
  n_agents: 10
  n_objects: 2
  box_size: 100.0
  num_steps_lax: 4
  dt: 0.1
  freq: 40
  neighbor_radius: 100.0
  to_jit: True
  use_fori_loop: False
  log_level: INFO
agents:
  positions:
objects:
  positions: