name: CI 
on:
  push:
    branches: [ "main", "automated_tests" ]
  pull_request:
    branches: [ "main", "automated_tests" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    services:
      server:
        image: python:${{ matrix.python-version }}
        options: python:${{ matrix.python-version }} scripts/run_server.py
      interface:
        image: python:${{ matrix.python-version }}
        options: panel serve scripts/run_server.py
        ports:
          - 5006:5006
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Check format with black 
      run: |
        black . --diff --color 
    - name: Test with pytest
      run: |
        pytest
    - name: Test server
      run: curl -I http://localhost:5006