name: CI 
on:
  push:
    branches: [ "main", "automated_tests" ]
  pull_request:
    branches: [ "main", "automated_tests" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Check format with black 
      run: |
        black . --diff --color 
    - name: Test with pytest
      run: |
        pytest
    - name: Run server
      run: python scripts/run_server.py &
        sleep 5
    - name: Run interface
      run: python scripts/run_interface.py &
        sleep 5 &&
        curl http://localhost:5006 -I